export const tz: TimezoneRegion[] = [
  {
    region: "america",
    timezones: [
      { offset: "GMT-11:00", id: "Pacific/Midway", name: "Pacific/Midway" },
      { offset: "GMT-10:00", id: "America/Adak", name: "America/Adak" },
      {
        offset: "GMT-09:00",
        id: "America/Anchorage",
        name: "America/Anchorage",
      },
      { offset: "GMT-09:00", id: "Pacific/Gambier", name: "Pacific/Gambier" },
      {
        offset: "GMT-08:00",
        id: "America/Dawson_Creek",
        name: "America/Dawson Creek",
      },
      { offset: "GMT-08:00", id: "America/Ensenada", name: "America/Ensenada" },
      {
        offset: "GMT-08:00",
        id: "America/Los_Angeles",
        name: "America/Los Angeles",
      },
      {
        offset: "GMT-07:00",
        id: "America/Chihuahua",
        name: "America/Chihuahua",
      },
      { offset: "GMT-07:00", id: "America/Denver", name: "America/Denver" },
      { offset: "GMT-06:00", id: "America/Belize", name: "America/Belize" },
      { offset: "GMT-06:00", id: "America/Cancun", name: "America/Cancun" },
      { offset: "GMT-06:00", id: "America/Chicago", name: "America/Chicago" },
      {
        offset: "GMT-06:00",
        id: "Chile/EasterIsland",
        name: "Chile/EasterIsland",
      },
      { offset: "GMT-05:00", id: "America/Bogota", name: "America/Bogota" },
      { offset: "GMT-05:00", id: "America/Havana", name: "America/Havana" },
      { offset: "GMT-05:00", id: "America/New_York", name: "America/New York" },
      { offset: "GMT-04:30", id: "America/Caracas", name: "America/Caracas" },
      {
        offset: "GMT-04:00",
        id: "America/Campo_Grande",
        name: "America/Campo Grande",
      },
      {
        offset: "GMT-04:00",
        id: "America/Glace_Bay",
        name: "America/Glace Bay",
      },
      {
        offset: "GMT-04:00",
        id: "America/Goose_Bay",
        name: "America/Goose Bay",
      },
      { offset: "GMT-04:00", id: "America/Santiago", name: "America/Santiago" },
      { offset: "GMT-04:00", id: "America/La_Paz", name: "America/La Paz" },
      {
        offset: "GMT-03:00",
        id: "America/Argentina/Buenos_Aires",
        name: "America/Argentina/Buenos Aires",
      },
      {
        offset: "GMT-03:00",
        id: "America/Montevideo",
        name: "America/Montevideo",
      },
      {
        offset: "GMT-03:00",
        id: "America/Araguaina",
        name: "America/Araguaina",
      },
      { offset: "GMT-03:00", id: "America/Godthab", name: "America/Godthab" },
      { offset: "GMT-03:00", id: "America/Miquelon", name: "America/Miquelon" },
      {
        offset: "GMT-03:00",
        id: "America/Sao_Paulo",
        name: "America/Sao Paulo",
      },
      { offset: "GMT-03:30", id: "America/St_Johns", name: "America/St Johns" },
      { offset: "GMT-02:00", id: "America/Noronha", name: "America/Noronha" },
    ],
  },
  {
    region: "atlantic",
    timezones: [
      {
        offset: "GMT-01:00",
        id: "Atlantic/Cape_Verde",
        name: "Atlantic/Cape Verde",
      },
      { offset: "GMT+01:00", id: "Atlantic/Azores", name: "Atlantic/Azores" },
      { offset: "GMT+01:00", id: "Atlantic/Stanley", name: "Atlantic/Stanley" },
    ],
  },
  {
    region: "europe",
    timezones: [
      { offset: "GMT", id: "Europe/Belfast", name: "Europe/Belfast" },
      { offset: "GMT", id: "Europe/Dublin", name: "Europe/Dublin" },
      { offset: "GMT", id: "Europe/Lisbon", name: "Europe/Lisbon" },
      { offset: "GMT", id: "Europe/London", name: "Europe/London" },
      { offset: "GMT+01:00", id: "Europe/Amsterdam", name: "Europe/Amsterdam" },
      { offset: "GMT+01:00", id: "Europe/Belgrade", name: "Europe/Belgrade" },
      { offset: "GMT+01:00", id: "Europe/Brussels", name: "Europe/Brussels" },
    ],
  },
  {
    region: "africa",
    timezones: [
      { offset: "GMT", id: "Africa/Abidjan", name: "Africa/Abidjan" },
      { offset: "GMT+01:00", id: "Africa/Algiers", name: "Africa/Algiers" },
      { offset: "GMT+01:00", id: "Africa/Windhoek", name: "Africa/Windhoek" },
      { offset: "GMT+02:00", id: "Africa/Cairo", name: "Africa/Cairo" },
      { offset: "GMT+02:00", id: "Africa/Blantyre", name: "Africa/Blantyre" },
      {
        offset: "GMT+03:00",
        id: "Africa/Addis_Ababa",
        name: "Africa/Addis Ababa",
      },
    ],
  },
  {
    region: "asia",
    timezones: [
      { offset: "GMT+02:00", id: "Asia/Beirut", name: "Asia/Beirut" },
      { offset: "GMT+02:00", id: "Asia/Damascus", name: "Asia/Damascus" },
      { offset: "GMT+02:00", id: "Asia/Gaza", name: "Asia/Gaza" },
      { offset: "GMT+02:00", id: "Asia/Jerusalem", name: "Asia/Jerusalem" },
      { offset: "GMT+03:00", id: "Asia/Riyadh89", name: "Asia/Riyadh89" },
      { offset: "GMT+03:30", id: "Asia/Tehran", name: "Asia/Tehran" },
      { offset: "GMT+04:00", id: "Asia/Dubai", name: "Asia/Dubai" },
      { offset: "GMT+04:00", id: "Asia/Yerevan", name: "Asia/Yerevan" },
      { offset: "GMT+04:30", id: "Asia/Kabul", name: "Asia/Kabul" },
      { offset: "GMT+05:00", id: "Asia/Tashkent", name: "Asia/Tashkent" },
      { offset: "GMT+05:30", id: "Asia/Kolkata", name: "Asia/Kolkata" },
      { offset: "GMT+05:45", id: "Asia/Katmandu", name: "Asia/Katmandu" },
      { offset: "GMT+06:00", id: "Asia/Dhaka", name: "Asia/Dhaka" },
      { offset: "GMT+06:30", id: "Asia/Rangoon", name: "Asia/Rangoon" },
      { offset: "GMT+07:00", id: "Asia/Bangkok", name: "Asia/Bangkok" },
      { offset: "GMT+07:00", id: "Asia/Novosibirsk", name: "Asia/Novosibirsk" },
      { offset: "GMT+08:00", id: "Asia/Hong_Kong", name: "Asia/Hong Kong" },
      { offset: "GMT+08:00", id: "Asia/Krasnoyarsk", name: "Asia/Krasnoyarsk" },
      { offset: "GMT+09:00", id: "Asia/Irkutsk", name: "Asia/Irkutsk" },
      { offset: "GMT+09:00", id: "Asia/Seoul", name: "Asia/Seoul" },
      { offset: "GMT+09:00", id: "Asia/Tokyo", name: "Asia/Tokyo" },
      { offset: "GMT+10:00", id: "Asia/Yakutsk", name: "Asia/Yakutsk" },
      { offset: "GMT+11:00", id: "Asia/Vladivostok", name: "Asia/Vladivostok" },
      { offset: "GMT+12:00", id: "Asia/Anadyr", name: "Asia/Anadyr" },
      { offset: "GMT+12:00", id: "Asia/Magadan", name: "Asia/Magadan" },
    ],
  },
  {
    region: "australia",
    timezones: [
      { offset: "GMT+08:00", id: "Australia/Perth", name: "Australia/Perth" },
      { offset: "GMT+08:45", id: "Australia/Eucla", name: "Australia/Eucla" },
      {
        offset: "GMT+09:30",
        id: "Australia/Adelaide",
        name: "Australia/Adelaide",
      },
      { offset: "GMT+09:30", id: "Australia/Darwin", name: "Australia/Darwin" },
      {
        offset: "GMT+10:00",
        id: "Australia/Brisbane",
        name: "Australia/Brisbane",
      },
      { offset: "GMT+10:00", id: "Australia/Hobart", name: "Australia/Hobart" },
      {
        offset: "GMT+10:30",
        id: "Australia/Lord_Howe",
        name: "Australia/Lord Howe",
      },
    ],
  },
  {
    region: "pacific",
    timezones: [
      { offset: "GMT-09:00", id: "Pacific/Gambier", name: "Pacific/Gambier" },
      {
        offset: "GMT-09:30",
        id: "Pacific/Marquesas",
        name: "Pacific/Marquesas",
      },
      { offset: "GMT-11:30", id: "Pacific/Norfolk", name: "Pacific/Norfolk" },
      { offset: "GMT+12:00", id: "Pacific/Auckland", name: "Pacific/Auckland" },
      { offset: "GMT+12:45", id: "Pacific/Chatham", name: "Pacific/Chatham" },
      {
        offset: "GMT+13:00",
        id: "Pacific/Tongatapu",
        name: "Pacific/Tongatapu",
      },
      {
        offset: "GMT+14:00",
        id: "Pacific/Kiritimati",
        name: "Pacific/Kiritimati",
      },
    ],
  },
  {
    region: "etc",
    timezones: [
      { offset: "GMT-12:00", id: "Etc/GMT-12", name: "Etc/GMT-12" },
      { offset: "GMT-11:00", id: "Etc/GMT-11", name: "Etc/GMT-11" },
      { offset: "GMT+08:00", id: "Etc/GMT+8", name: "Etc/GMT+8" },
      { offset: "GMT+10:00", id: "Etc/GMT+10", name: "Etc/GMT+10" },
      { offset: "GMT+12:00", id: "Etc/GMT+12", name: "Etc/GMT+12" },
    ],
  },
];
